// Every editable list on the website is defined here.
// Adding a field here automatically adds it to the admin form.

const ICONS = ['home', 'heart', 'key', 'shield', 'users', 'leaf', 'compass', 'briefcase', 'phone', 'star', 'sun', 'book', 'bed', 'hand', 'chat'];

const COLLECTIONS = {
  rooms: {
    label: 'Rooms', singular: 'Room', icon: 'bed', titleField: 'title',
    help: 'Advertise rooms. Change the status to "Let / allocated" (or switch off "Show on website") as soon as a room is taken.',
    listColumns: ['ref', 'status', 'area', 'available_from'],
    fields: [
      { name: 'title', label: 'Listing title', type: 'text', required: true, placeholder: 'e.g. Bright double room with garden view' },
      { name: 'ref', label: 'Room reference', type: 'text', help: 'Shown to enquirers and added to WhatsApp messages so staff know which room they mean. Leave blank to auto-generate.' },
      { name: 'status', label: 'Status', type: 'select', options: ['Available now', 'Available soon', 'Under offer', 'Let / allocated'], default: 'Available now', help: '"Let / allocated" rooms are hidden from the public automatically.' },
      { name: 'property', label: 'Property name', type: 'text', placeholder: 'e.g. Grove House' },
      { name: 'area', label: 'Area', type: 'text', placeholder: 'e.g. Handsworth' },
      { name: 'postcode', label: 'Postcode area (public)', type: 'text', placeholder: 'e.g. B21', help: 'Only the first part is recommended, for tenant safety.' },
      { name: 'room_type', label: 'Room type', type: 'select', options: ['Single room', 'Double room', 'En-suite room', 'Studio', 'Self-contained flat'] },
      { name: 'rent', label: 'Rent / funding', type: 'text', placeholder: 'e.g. Housing Benefit eligible' },
      { name: 'available_from', label: 'Available from', type: 'date' },
      { name: 'suitable_for', label: 'Suitable for', type: 'text', placeholder: 'e.g. Single adults 18+, male' },
      { name: 'furnished', label: 'Fully furnished', type: 'checkbox', default: true },
      { name: 'bills_included', label: 'Bills included', type: 'checkbox', default: true },
      { name: 'features', label: 'Key features', type: 'list', help: 'One per line, e.g. "Free Wi-Fi".' },
      { name: 'summary', label: 'Short summary', type: 'textarea', help: 'One or two sentences shown on the room card.' },
      { name: 'description', label: 'Full description', type: 'rich' },
      { name: 'images', label: 'Photographs', type: 'images', help: 'The first photo is the cover. Drag to reorder. Click a photo to set the focal point.' },
      { name: 'featured', label: 'Feature on home page', type: 'checkbox' },
    ],
  },
  events: {
    label: 'Events', singular: 'Event', icon: 'calendar', titleField: 'title',
    help: 'Monthly activities and events. Set the number of spaces and bookings close automatically when full.',
    listColumns: ['date', 'start_time', 'location', 'capacity'],
    fields: [
      { name: 'title', label: 'Event name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'select', options: ['Social', 'Sport', 'Wellbeing', 'Skills & learning', 'Day trip', 'Community'] },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'start_time', label: 'Start time', type: 'time' },
      { name: 'end_time', label: 'End time', type: 'time' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'capacity', label: 'Number of spaces', type: 'number', help: 'Leave blank for unlimited.' },
      { name: 'registration_open', label: 'Allow online registration', type: 'checkbox', default: true },
      { name: 'summary', label: 'Short description', type: 'textarea' },
      { name: 'description', label: 'Full description', type: 'rich' },
      { name: 'image', label: 'Photograph', type: 'image' },
    ],
  },
  stories: {
    label: "Tenants' stories", singular: 'Story', icon: 'star', titleField: 'title',
    help: 'Only publish with written consent. Stories without the consent box ticked will not appear on the website.',
    listColumns: ['date', 'category', 'consent'],
    fields: [
      { name: 'title', label: 'Story title', type: 'text', required: true },
      { name: 'date', label: 'Date', type: 'date' },
      { name: 'category', label: 'Category', type: 'select', options: ['Personal achievement', 'Sport', 'Community', 'Milestone', 'Wellbeing', 'Education & work'] },
      { name: 'person', label: 'Name shown', type: 'text', help: 'Use first name or initial only, or leave blank to stay anonymous.' },
      { name: 'related_event', label: 'Related activity / event', type: 'text' },
      { name: 'summary', label: 'Short introduction', type: 'textarea' },
      { name: 'body', label: 'Story', type: 'rich' },
      { name: 'quote', label: 'Pull quote (optional)', type: 'textarea' },
      { name: 'images', label: 'Photographs', type: 'images' },
      { name: 'consent', label: 'I confirm written consent is held for this story and every photograph', type: 'checkbox', required: true },
    ],
  },
  news: {
    label: 'News & newsletters', singular: 'Post', icon: 'book', titleField: 'title',
    help: 'Share news and the monthly newsletter. Attach a PDF to offer a download.',
    listColumns: ['date', 'category'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'date', label: 'Date', type: 'date' },
      { name: 'category', label: 'Type', type: 'select', options: ['Newsletter', 'News', 'Update'] },
      { name: 'summary', label: 'Summary', type: 'textarea' },
      { name: 'body', label: 'Article', type: 'rich' },
      { name: 'image', label: 'Cover image', type: 'image' },
      { name: 'attachment', label: 'Newsletter PDF (optional)', type: 'file' },
    ],
  },
  services: {
    label: 'Services', singular: 'Service', icon: 'heart', titleField: 'title',
    help: 'Each service appears on the Services page and home page. Drag to change order.',
    listColumns: ['audience'],
    fields: [
      { name: 'title', label: 'Service name', type: 'text', required: true },
      { name: 'icon', label: 'Icon', type: 'select', options: ICONS },
      { name: 'audience', label: 'Who it is for', type: 'text', placeholder: 'e.g. Tenants, referral agencies' },
      { name: 'summary', label: 'Short summary', type: 'textarea' },
      { name: 'body', label: 'Full details', type: 'rich' },
      { name: 'points', label: 'What is included', type: 'list', help: 'One per line.' },
      { name: 'image', label: 'Image (optional)', type: 'image' },
    ],
  },
  partners: {
    label: 'Working together', singular: 'Partner', icon: 'users', titleField: 'name',
    help: 'Referral agencies, accrediting bodies and community & sporting partnerships (e.g. the cricket and badminton teams).',
    listColumns: ['category', 'website'],
    fields: [
      { name: 'name', label: 'Organisation / team name', type: 'text', required: true },
      { name: 'category', label: 'Section', type: 'select', options: ['Referral agency', 'Accrediting body', 'Community & sport'] },
      { name: 'logo', label: 'Logo', type: 'image', help: 'PNG with transparent background works best.' },
      { name: 'description', label: 'About this partnership', type: 'rich' },
      { name: 'website', label: 'Website link', type: 'url' },
      { name: 'images', label: 'Team / activity photographs', type: 'images' },
    ],
  },
  documents: {
    label: 'Documents & downloads', singular: 'Document', icon: 'file', titleField: 'title',
    help: 'Upload a new file to replace an existing one. The link on the website stays the same.',
    listColumns: ['section', 'file'],
    fields: [
      { name: 'title', label: 'Document title', type: 'text', required: true },
      { name: 'section', label: 'Show on page', type: 'select', options: ['Referrals', 'Charter of Rights', 'Complaints', 'Tenants', 'General'] },
      { name: 'description', label: 'Short description', type: 'textarea' },
      { name: 'file', label: 'File (PDF, Word, etc.)', type: 'file', required: true },
    ],
  },
};

module.exports = { COLLECTIONS, ICONS };
