// Every piece of editable page text and imagery.
// Staff edit these in Admin → Page content, or directly on the page with "Edit this page".

const img = (name) => JSON.stringify({ src: `/img/placeholders/${name}.svg`, x: 50, y: 50 });

const PAGES = [
  {
    id: 'global', label: 'Site-wide', path: '/',
    fields: [
      { key: 'global.tagline', label: 'Footer strapline', type: 'textarea', def: 'Safe, supported homes in Birmingham, and the encouragement to build what comes next.' },
      { key: 'global.cta.title', label: 'Referral banner title', type: 'text', def: 'Know someone who needs a safe place to stay?' },
      { key: 'global.cta.text', label: 'Referral banner text', type: 'textarea', def: 'We work with referral agencies, support workers and professionals across Birmingham. Referrals are quick, and we aim to respond within one working day.' },
      { key: 'global.wa.label', label: 'WhatsApp button label', type: 'text', def: 'Message us on WhatsApp' },
      { key: 'global.newsletter.title', label: 'Newsletter sign-up title', type: 'text', def: 'Get our monthly newsletter' },
      { key: 'global.newsletter.text', label: 'Newsletter sign-up text', type: 'textarea', def: 'Upcoming activities, tenant achievements and news from the Solace community, once a month.' },
    ],
  },
  {
    id: 'home', label: 'Home page', path: '/',
    fields: [
      { key: 'home.hero.eyebrow', label: 'Hero small heading', type: 'text', def: 'Supported housing · Birmingham' },
      { key: 'home.hero.title', label: 'Hero title', type: 'text', def: 'A safe place to land. A real chance to grow.' },
      { key: 'home.hero.text', label: 'Hero introduction', type: 'textarea', def: 'Solace Housing provides safe, furnished and supported homes for adults who need a fresh start, with a team who know every tenant by name and stay alongside them for every step.' },
      { key: 'home.hero.image', label: 'Hero image', type: 'image', def: img('lounge') },
      { key: 'home.hero.badge', label: 'Hero image badge', type: 'text', def: 'Support that feels like home' },
      { key: 'home.intro.eyebrow', label: 'Intro small heading', type: 'text', def: 'Who we are' },
      { key: 'home.intro.title', label: 'Intro title', type: 'text', def: 'More than a room. A community that has your back.' },
      { key: 'home.intro.text', label: 'Intro text', type: 'rich', def: 'Solace Housing is a Birmingham-based supported housing provider. We offer good-quality, fully furnished rooms alongside practical, person-centred support, so the people we house can feel settled, stay safe and move forward with confidence.\n\nFrom help with benefits and budgeting to monthly community activities, our cricket and badminton teams, and simply someone to talk to, we build the kind of stability that lasts.' },
      { key: 'home.intro.image', label: 'Intro image', type: 'image', def: img('community') },
      { key: 'home.stat1.value', label: 'Highlight 1 value', type: 'text', def: '7 days' },
      { key: 'home.stat1.label', label: 'Highlight 1 label', type: 'text', def: 'a week, a team you can reach' },
      { key: 'home.stat2.value', label: 'Highlight 2 value', type: 'text', def: '1:1' },
      { key: 'home.stat2.label', label: 'Highlight 2 label', type: 'text', def: 'key worker for every tenant' },
      { key: 'home.stat3.value', label: 'Highlight 3 value', type: 'text', def: '100%' },
      { key: 'home.stat3.label', label: 'Highlight 3 label', type: 'text', def: 'furnished rooms, bills included' },
      { key: 'home.stat4.value', label: 'Highlight 4 value', type: 'text', def: 'Monthly' },
      { key: 'home.stat4.label', label: 'Highlight 4 label', type: 'text', def: 'community activities & trips' },
      { key: 'home.rooms.title', label: 'Rooms section title', type: 'text', def: 'Rooms available now' },
      { key: 'home.rooms.text', label: 'Rooms section text', type: 'textarea', def: 'Clean, warm and fully furnished rooms across Birmingham, ready to move into. Enquire in seconds on WhatsApp.' },
      { key: 'home.services.title', label: 'Services section title', type: 'text', def: 'How we support people' },
      { key: 'home.services.text', label: 'Services section text', type: 'textarea', def: 'Every tenancy comes with support shaped around the person: their goals, their pace, their next step.' },
      { key: 'home.life.title', label: 'Community section title', type: 'text', def: 'Life at Solace' },
      { key: 'home.life.text', label: 'Community section text', type: 'textarea', def: 'Cricket on a Saturday, badminton on a weeknight, a community lunch every month. Belonging is part of the support.' },
      { key: 'home.partners.title', label: 'Partners strip title', type: 'text', def: 'Working together across Birmingham' },
    ],
  },
  {
    id: 'about', label: 'About us', path: '/about',
    fields: [
      { key: 'about.hero.title', label: 'Page title', type: 'text', def: 'About Solace Housing' },
      { key: 'about.hero.text', label: 'Page introduction', type: 'textarea', def: 'We believe everyone deserves a safe, settled home and people around them who believe in them.' },
      { key: 'about.who.title', label: 'Who we are: title', type: 'text', def: 'Who we are' },
      { key: 'about.who.text', label: 'Who we are: text', type: 'rich', def: 'Solace Housing is a supported housing provider based in Birmingham. We provide safe, good-quality accommodation for adults who need a secure place to live and a little extra support to get back on their feet.\n\nOur team combines housing management with hands-on support. We know our tenants, we know our properties and we take pride in both.' },
      { key: 'about.who.image', label: 'Who we are: image', type: 'image', def: img('house') },
      { key: 'about.what.title', label: 'What we do: title', type: 'text', def: 'What we do' },
      { key: 'about.what.text', label: 'What we do: text', type: 'rich', def: 'We provide furnished, well-maintained rooms with bills included, and wrap practical support around every tenancy. That means help with benefits and budgeting, links to health and wellbeing services, support into education, training and work, and a steady presence when life gets difficult.\n\nWe work closely with referral agencies, local services and community partners so nobody has to navigate things alone.' },
      { key: 'about.what.image', label: 'What we do: image', type: 'image', def: img('keys') },
      { key: 'about.values.title', label: 'Values title', type: 'text', def: 'Our values' },
      { key: 'about.value1.title', label: 'Value 1', type: 'text', def: 'Respect' },
      { key: 'about.value1.text', label: 'Value 1 text', type: 'textarea', def: 'Everyone is treated with dignity, listened to and given a real say in their own support.' },
      { key: 'about.value2.title', label: 'Value 2', type: 'text', def: 'Safety' },
      { key: 'about.value2.text', label: 'Value 2 text', type: 'textarea', def: 'Secure, well-kept homes and a safeguarding-first approach in everything we do.' },
      { key: 'about.value3.title', label: 'Value 3', type: 'text', def: 'Belonging' },
      { key: 'about.value3.text', label: 'Value 3 text', type: 'textarea', def: 'A community to be part of, through shared activities, sport and simply getting to know each other.' },
      { key: 'about.value4.title', label: 'Value 4', type: 'text', def: 'Progress' },
      { key: 'about.value4.text', label: 'Value 4 text', type: 'textarea', def: 'Small steps count. We celebrate every milestone on the way to independence.' },
      { key: 'about.approach.title', label: 'Our approach: title', type: 'text', def: 'Our approach to support' },
      { key: 'about.approach.text', label: 'Our approach: introduction', type: 'textarea', def: 'Support at Solace is person-centred, strengths-based and trauma-informed. It follows a simple rhythm.' },
      { key: 'about.step1.title', label: 'Approach step 1', type: 'text', def: 'Welcome' },
      { key: 'about.step1.text', label: 'Approach step 1 text', type: 'textarea', def: 'A warm move-in, a tour of your home and a chance to meet your key worker in your first days.' },
      { key: 'about.step2.title', label: 'Approach step 2', type: 'text', def: 'Understand' },
      { key: 'about.step2.text', label: 'Approach step 2 text', type: 'textarea', def: 'Together we build a support plan around your goals, strengths and any risks, in your words.' },
      { key: 'about.step3.title', label: 'Approach step 3', type: 'text', def: 'Support' },
      { key: 'about.step3.text', label: 'Approach step 3 text', type: 'textarea', def: 'Regular key-work sessions, practical help and links to specialist services when they are needed.' },
      { key: 'about.step4.title', label: 'Approach step 4', type: 'text', def: 'Move on' },
      { key: 'about.step4.text', label: 'Approach step 4 text', type: 'textarea', def: 'When you are ready, we help you plan and prepare for a settled, independent next home.' },
    ],
  },
  {
    id: 'services', label: 'Services', path: '/services',
    fields: [
      { key: 'services.hero.title', label: 'Page title', type: 'text', def: 'Our services' },
      { key: 'services.hero.text', label: 'Page introduction', type: 'textarea', def: 'Housing and support designed around people, with clear information for tenants, referral agencies and partner organisations.' },
      { key: 'services.audience.title', label: 'Audience section title', type: 'text', def: 'Information for you' },
      { key: 'services.aud1.title', label: 'Audience 1', type: 'text', def: 'Existing tenants' },
      { key: 'services.aud1.text', label: 'Audience 1 text', type: 'textarea', def: 'Report a repair, book onto an activity, read your Charter of Rights or speak to your key worker.' },
      { key: 'services.aud2.title', label: 'Audience 2', type: 'text', def: 'Looking for a room' },
      { key: 'services.aud2.text', label: 'Audience 2 text', type: 'textarea', def: 'See what is available now and message us on WhatsApp. We will talk you through the next steps.' },
      { key: 'services.aud3.title', label: 'Audience 3', type: 'text', def: 'Referral agencies' },
      { key: 'services.aud3.text', label: 'Audience 3 text', type: 'textarea', def: 'Download our referral form, check eligibility and find out how quickly we can respond.' },
      { key: 'services.aud4.title', label: 'Audience 4', type: 'text', def: 'Partners & organisations' },
      { key: 'services.aud4.text', label: 'Audience 4 text', type: 'textarea', def: 'From community groups to commissioners, we would love to hear how we can work together.' },
    ],
  },
  {
    id: 'rooms', label: 'Rooms available', path: '/rooms',
    fields: [
      { key: 'rooms.hero.title', label: 'Page title', type: 'text', def: 'Rooms available' },
      { key: 'rooms.hero.text', label: 'Page introduction', type: 'textarea', def: 'Every room is fully furnished with bills included and comes with support from our team. Found one you like? Message us on WhatsApp. No long forms.' },
      { key: 'rooms.empty', label: 'Message when no rooms are available', type: 'textarea', def: 'All of our rooms are currently allocated. New rooms become available regularly, so message us on WhatsApp and we will let you know.' },
      { key: 'rooms.how.title', label: 'How it works title', type: 'text', def: 'How to get a room' },
      { key: 'rooms.how1', label: 'Step 1', type: 'text', def: 'Message us on WhatsApp or fill in the contact form' },
      { key: 'rooms.how2', label: 'Step 2', type: 'text', def: 'We have a friendly chat about your situation' },
      { key: 'rooms.how3', label: 'Step 3', type: 'text', def: 'View the room and meet the team' },
      { key: 'rooms.how4', label: 'Step 4', type: 'text', def: 'Move in with your support plan in place' },
    ],
  },
  {
    id: 'referrals', label: 'Referrals', path: '/referrals',
    fields: [
      { key: 'referrals.hero.title', label: 'Page title', type: 'text', def: 'Make a referral' },
      { key: 'referrals.hero.text', label: 'Page introduction', type: 'textarea', def: 'For referral agencies, support workers and professionals. Simple, quick and responsive.' },
      { key: 'referrals.who.title', label: 'Who we accept: title', type: 'text', def: 'Who we can support' },
      { key: 'referrals.who.text', label: 'Who we accept: text', type: 'rich', def: 'We accept referrals for adults aged 18 and over who need supported accommodation in Birmingham, including people:\n\n- leaving hospital, custody or other institutions\n- at risk of or experiencing homelessness\n- with low to medium support needs around mental health, substance use or independent living skills\n- moving on from other supported settings\n\nIf you are not sure whether someone is a good fit, call or WhatsApp us. We are always happy to talk it through.' },
      { key: 'referrals.steps.title', label: 'How to refer: title', type: 'text', def: 'How to submit a referral' },
      { key: 'referrals.step1', label: 'Step 1', type: 'textarea', def: 'Download the referral form below and complete every section as fully as you can.' },
      { key: 'referrals.step2', label: 'Step 2', type: 'textarea', def: 'Attach any recent risk assessment and support plan you hold for the applicant.' },
      { key: 'referrals.step3', label: 'Step 3', type: 'textarea', def: 'Email the completed form to our referrals inbox, or upload it using the secure form on this page.' },
      { key: 'referrals.step4', label: 'Step 4', type: 'textarea', def: 'We review every referral and aim to respond within one working day, arranging an assessment where appropriate.' },
      { key: 'referrals.note', label: 'Important note', type: 'textarea', def: 'Please make sure the applicant has consented to the referral and to their information being shared with Solace Housing.' },
    ],
  },
  {
    id: 'working', label: 'Working together', path: '/working-together',
    fields: [
      { key: 'working.hero.title', label: 'Page title', type: 'text', def: 'Working together' },
      { key: 'working.hero.text', label: 'Page introduction', type: 'textarea', def: 'Good support is never delivered alone. Meet the organisations, professional bodies and teams we are proud to work alongside.' },
      { key: 'working.referral.title', label: 'Referral agencies title', type: 'text', def: 'Referral agencies' },
      { key: 'working.referral.text', label: 'Referral agencies text', type: 'textarea', def: 'We work closely with statutory and voluntary services across Birmingham to make sure people get the right home at the right time.' },
      { key: 'working.accredit.title', label: 'Accrediting bodies title', type: 'text', def: 'Accreditation & professional bodies' },
      { key: 'working.accredit.text', label: 'Accrediting bodies text', type: 'textarea', def: 'The standards and professional bodies that help us deliver safe, high-quality housing and support.' },
      { key: 'working.community.title', label: 'Community & sport title', type: 'text', def: 'Community & sporting partnerships' },
      { key: 'working.community.text', label: 'Community & sport text', type: 'textarea', def: 'Sport and shared activity build confidence, friendships and routine. Our tenants play, train and compete together.' },
      { key: 'working.join.title', label: 'Partner call-to-action title', type: 'text', def: 'Want to partner with us?' },
      { key: 'working.join.text', label: 'Partner call-to-action text', type: 'textarea', def: 'Whether you are a referral agency, a local business or a community group, get in touch. We would love to hear from you.' },
    ],
  },
  {
    id: 'repairs', label: 'Report a repair', path: '/repairs',
    fields: [
      { key: 'repairs.hero.title', label: 'Page title', type: 'text', def: 'Report a repair or damp' },
      { key: 'repairs.hero.text', label: 'Page introduction', type: 'textarea', def: 'Tell us what is wrong and we will get it sorted. Photos help us send the right person first time.' },
      { key: 'repairs.emergency.title', label: 'Emergency box title', type: 'text', def: 'Is it an emergency?' },
      { key: 'repairs.emergency.text', label: 'Emergency box text', type: 'textarea', def: 'For a gas leak, call the National Gas Emergency line on 0800 111 999. For fire or immediate danger, call 999. For flooding, no heating in winter, a failed front door lock or loss of power, please call us straight away. Do not use this form.' },
      { key: 'repairs.damp.title', label: 'Damp & mould box title', type: 'text', def: 'Damp and mould' },
      { key: 'repairs.damp.text', label: 'Damp & mould box text', type: 'textarea', def: 'We take damp and mould seriously. Please report it as soon as you notice it, even if it looks small. We will inspect, find the cause and keep you updated until it is fixed.' },
      { key: 'repairs.success', label: 'Message after submitting', type: 'textarea', def: 'Thank you. Your repair has been reported and our team has been notified. We will be in touch to arrange a visit. Please keep your reference number.' },
    ],
  },
  {
    id: 'events', label: 'Events', path: '/events',
    fields: [
      { key: 'events.hero.title', label: 'Page title', type: 'text', def: 'Events & activities' },
      { key: 'events.hero.text', label: 'Page introduction', type: 'textarea', def: 'Something to look forward to every month: trips, sport, food and good company. Reserve your space online.' },
      { key: 'events.empty', label: 'Message when no events', type: 'textarea', def: 'New activities are being planned. Check back soon or ask your key worker.' },
    ],
  },
  {
    id: 'stories', label: "Tenants' stories", path: '/stories',
    fields: [
      { key: 'stories.hero.title', label: 'Page title', type: 'text', def: "Our tenants' stories" },
      { key: 'stories.hero.text', label: 'Page introduction', type: 'textarea', def: 'Achievements big and small, shared with pride and with permission.' },
      { key: 'stories.consent', label: 'Consent statement', type: 'textarea', def: 'Every story and photograph on this page is shared with the written consent of the people involved. Names may be shortened or changed to protect privacy. If you would like something removed, contact us and we will take it down straight away.' },
    ],
  },
  {
    id: 'news', label: 'News & newsletter', path: '/news',
    fields: [
      { key: 'news.hero.title', label: 'Page title', type: 'text', def: 'News & newsletter' },
      { key: 'news.hero.text', label: 'Page introduction', type: 'textarea', def: 'Updates from Solace Housing and our monthly community newsletter.' },
    ],
  },
  {
    id: 'charter', label: 'Charter of Rights', path: '/charter-of-rights',
    fields: [
      { key: 'charter.hero.title', label: 'Page title', type: 'text', def: 'Charter of Rights' },
      { key: 'charter.hero.text', label: 'Page introduction', type: 'textarea', def: 'What you can expect from us and what we ask of each other.' },
      { key: 'charter.what.title', label: 'What is it: title', type: 'text', def: 'What is the Charter of Rights?' },
      { key: 'charter.what.text', label: 'What is it: text', type: 'rich', def: 'Our Charter of Rights sets out, in plain language, the rights every Solace Housing tenant has and the standards of service we commit to. It sits alongside your licence or tenancy agreement and your support plan.' },
      { key: 'charter.why.title', label: 'Why it matters: title', type: 'text', def: 'Why it matters' },
      { key: 'charter.why.text', label: 'Why it matters: text', type: 'rich', def: 'Knowing your rights helps you feel safe, speak up and get the most from your home and support. It also holds us to account: if we fall short, the charter explains what you can do about it.' },
      { key: 'charter.right1.title', label: 'Right 1', type: 'text', def: 'A safe, decent home' },
      { key: 'charter.right1.text', label: 'Right 1 text', type: 'textarea', def: 'Your home will be clean, secure, well maintained and meet all safety standards, with repairs dealt with promptly.' },
      { key: 'charter.right2.title', label: 'Right 2', type: 'text', def: 'Dignity and respect' },
      { key: 'charter.right2.text', label: 'Right 2 text', type: 'textarea', def: 'You will be treated fairly and without discrimination, and your culture, beliefs and choices will be respected.' },
      { key: 'charter.right3.title', label: 'Right 3', type: 'text', def: 'Privacy and confidentiality' },
      { key: 'charter.right3.text', label: 'Right 3 text', type: 'textarea', def: 'Your personal information is kept secure and only shared with your consent or where the law requires it.' },
      { key: 'charter.right4.title', label: 'Right 4', type: 'text', def: 'Support that fits you' },
      { key: 'charter.right4.text', label: 'Right 4 text', type: 'textarea', def: 'A named key worker and a support plan written with you, reviewed regularly and centred on your goals.' },
      { key: 'charter.right5.title', label: 'Right 5', type: 'text', def: 'A voice' },
      { key: 'charter.right5.text', label: 'Right 5 text', type: 'textarea', def: 'You can give feedback, join tenant meetings and help shape how Solace Housing is run.' },
      { key: 'charter.right6.title', label: 'Right 6', type: 'text', def: 'To complain and be heard' },
      { key: 'charter.right6.text', label: 'Right 6 text', type: 'textarea', def: 'You can raise a concern or complaint at any time, without it affecting your home or support.' },
    ],
  },
  {
    id: 'complaints', label: 'Complaints', path: '/complaints',
    fields: [
      { key: 'complaints.hero.title', label: 'Page title', type: 'text', def: 'Complaints' },
      { key: 'complaints.hero.text', label: 'Page introduction', type: 'textarea', def: 'If something is not right, we want to know. Here is exactly what happens when you raise a complaint.' },
      { key: 'complaints.how.title', label: 'How to complain: title', type: 'text', def: 'How to make a complaint' },
      { key: 'complaints.how.text', label: 'How to complain: text', type: 'rich', def: 'You can complain in whichever way suits you:\n\n- speak to any member of staff or your key worker\n- call or WhatsApp us\n- email us\n- use the complaint form on this page\n- ask a friend, family member, advocate or support worker to complain for you\n\nMaking a complaint will never affect your tenancy or the support you receive.' },
      { key: 'complaints.s1.title', label: 'Stage 1 title', type: 'text', def: 'We receive your complaint' },
      { key: 'complaints.s1.text', label: 'Stage 1 text', type: 'textarea', def: 'We log it and acknowledge it within 2 working days, confirming who will be handling it and how to reach them.' },
      { key: 'complaints.s2.title', label: 'Stage 2 title', type: 'text', def: 'We investigate' },
      { key: 'complaints.s2.text', label: 'Stage 2 text', type: 'textarea', def: 'A manager not involved in the issue looks into what happened, speaking with you, staff and anyone else relevant.' },
      { key: 'complaints.s3.title', label: 'Stage 3 title', type: 'text', def: 'We keep you informed' },
      { key: 'complaints.s3.text', label: 'Stage 3 text', type: 'textarea', def: 'We keep in touch in the way you prefer and tell you straight away if anything is going to take longer than expected.' },
      { key: 'complaints.s4.title', label: 'Stage 4 title', type: 'text', def: 'Stage 1 response' },
      { key: 'complaints.s4.text', label: 'Stage 4 text', type: 'textarea', def: 'We write to you with our findings, what we will put right and any lessons learned, within 10 working days.' },
      { key: 'complaints.s5.title', label: 'Stage 5 title', type: 'text', def: 'Stage 2 review' },
      { key: 'complaints.s5.text', label: 'Stage 5 text', type: 'textarea', def: 'Still unhappy? Ask for a review. A senior manager or director will look at your complaint afresh and respond within 20 working days.' },
      { key: 'complaints.s6.title', label: 'Stage 6 title', type: 'text', def: 'Concluded' },
      { key: 'complaints.s6.text', label: 'Stage 6 text', type: 'textarea', def: 'We confirm the final outcome in writing, make sure agreed actions happen, and use what we learned to improve.' },
      { key: 'complaints.escalate.title', label: 'Still dissatisfied: title', type: 'text', def: 'If you are still not satisfied' },
      { key: 'complaints.escalate.text', label: 'Still dissatisfied: text', type: 'rich', def: 'Once you have completed our process, you can take your complaint further. Depending on your circumstances, this may include the Housing Ombudsman Service, the Local Government and Social Care Ombudsman, or Birmingham City Council. We will tell you which applies to you in our final response and help you contact them.' },
    ],
  },
  {
    id: 'contact', label: 'Contact us', path: '/contact',
    fields: [
      { key: 'contact.hero.title', label: 'Page title', type: 'text', def: 'Contact us' },
      { key: 'contact.hero.text', label: 'Page introduction', type: 'textarea', def: 'Tenants, referral agencies, partners, neighbours: we are here to help. The fastest way to reach us is WhatsApp.' },
      { key: 'contact.form.title', label: 'Form title', type: 'text', def: 'Send us a message' },
      { key: 'contact.success', label: 'Message after submitting', type: 'textarea', def: 'Thank you for getting in touch. We have received your message and will reply as soon as we can, usually within one working day.' },
    ],
  },
  {
    id: 'privacy', label: 'Privacy policy', path: '/privacy',
    fields: [
      { key: 'privacy.title', label: 'Page title', type: 'text', def: 'Privacy policy' },
      { key: 'privacy.text', label: 'Policy text', type: 'rich', def: 'Solace Housing collects the information you give us through this website, such as your name, contact details and the details of your enquiry, repair report, referral or event booking, so that we can respond and provide our services.\n\nWe store this information securely, only share it where it is needed to help you or where the law requires it, and keep it only for as long as necessary.\n\nYou can ask to see, correct or delete the information we hold about you at any time by contacting us.' },
    ],
  },
];

const DEFAULTS = {};
const FIELD_INDEX = {};
for (const p of PAGES) for (const f of p.fields) { DEFAULTS[f.key] = f.def; FIELD_INDEX[f.key] = { ...f, page: p.id }; }

const SETTINGS = [
  { group: 'Contact details', fields: [
    { key: 'org_name', label: 'Organisation name', def: 'Solace Housing' },
    { key: 'phone', label: 'Telephone', def: '+44 7493 299381' },
    { key: 'email', label: 'Public email address', def: 'info@solacehousing.co.uk' },
    { key: 'address', label: 'Office address', type: 'textarea', def: 'Solace Housing\nBirmingham\nWest Midlands' },
    { key: 'map_query', label: 'Map location', help: 'Postcode or full address used for the map. Leave blank to use the office address.', def: 'Birmingham City Centre, UK' },
    { key: 'hours', label: 'Opening times', type: 'textarea', def: 'Monday to Friday: 9:00am – 5:00pm\nSaturday: 10:00am – 2:00pm\nSunday & bank holidays: Closed\nOut-of-hours emergency line available to tenants' },
    { key: 'company_line', label: 'Footer legal line', def: 'Solace Housing · Supported housing in Birmingham' },
  ]},
  { group: 'WhatsApp', fields: [
    { key: 'whatsapp', label: 'WhatsApp number', help: 'International format, digits only, e.g. 447493299381', def: '447493299381' },
    { key: 'wa_message', label: 'Default WhatsApp message', def: 'Hi Solace Housing, I would like some information about your rooms.' },
    { key: 'wa_room_message', label: 'Room enquiry message', help: 'Use {ref}, {title} and {area}. They are filled in automatically.', def: "Hi Solace Housing, I'm enquiring about room {ref}: {title} ({area}). Is it still available?" },
    { key: 'wa_float', label: 'Show floating WhatsApp button on every page', type: 'checkbox', def: '1' },
  ]},
  { group: 'Social media', fields: [
    { key: 'facebook', label: 'Facebook page URL', def: '' },
    { key: 'instagram', label: 'Instagram URL', def: '' },
    { key: 'tiktok', label: 'TikTok URL', def: '' },
    { key: 'linkedin', label: 'LinkedIn URL', def: '' },
  ]},
  { group: 'Email notifications', fields: [
    { key: 'inbox', label: 'Send form submissions to', help: 'Separate several addresses with commas.', def: 'info@solacehousing.co.uk' },
    { key: 'inbox_repairs', label: 'Send repair reports to (optional)', help: 'Leave blank to use the address above.', def: '' },
    { key: 'inbox_referrals', label: 'Send referrals to (optional)', def: '' },
    { key: 'smtp_host', label: 'SMTP server', help: 'From your email provider, e.g. smtp.office365.com or smtp.gmail.com', def: '' },
    { key: 'smtp_port', label: 'SMTP port', def: '587' },
    { key: 'smtp_user', label: 'SMTP username', def: '' },
    { key: 'smtp_pass', label: 'SMTP password / app password', type: 'password', def: '' },
    { key: 'mail_from', label: 'Send emails from', help: 'Usually the same as the SMTP username.', def: '' },
  ]},
  { group: 'Announcement', fields: [
    { key: 'announcement', label: 'Announcement bar text', help: 'Shown at the very top of every page. Leave blank to hide.', def: '' },
    { key: 'announcement_link', label: 'Announcement link', def: '' },
  ]},
];
const SETTING_DEFAULTS = {};
for (const g of SETTINGS) for (const f of g.fields) SETTING_DEFAULTS[f.key] = f.def;

module.exports = { PAGES, DEFAULTS, FIELD_INDEX, SETTINGS, SETTING_DEFAULTS };
